apiVersion: v1
kind: Service
metadata:
  name: pipemaster
  labels:
    app: pipemaster
spec:
  selector:
    app: pipemaster
  ports:
    - protocol: TCP
      port: 7681
      targetPort: 7681
  type: ClusterIP
